[package]
name = "rpdb"
version = "0.1.1"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies.postgres]
version = "0.15"
features = ["with-chrono"]

[dependencies]
chrono = "0.4"